const data = [
  {
    Timestamp: "10/6/2018 8:48:39",
    "Team number": "3501",
    "Match number": "16",
    "Scout name(your name)": "Bernice Lau",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver":
      "Robot got more than 3 fouls, Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 8:50:26",
    "Team number": "6174",
    "Match number": "16",
    "Scout name(your name)": "Christopher Linhardt",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 8:57:56",
    "Team number": "2643",
    "Match number": "16",
    "Scout name(your name)": "Jake Ryan ",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:14:45",
    "Team number": "1684",
    "Match number": "16",
    "Scout name(your name)": "Derek Duncan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "6",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "6",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:48:19",
    "Team number": "1458",
    "Match number": "16",
    "Scout name(your name)": "Audrey Lau",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "4",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:09:15",
    "Team number": "114",
    "Match number": "16.1",
    "Scout name(your name)": "Jessie Lin",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Dropped partner",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:16:33",
    "Team number": "114",
    "Match number": "16.2",
    "Scout name(your name)": "Jessie Lin",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 8:56:41",
    "Team number": "1967",
    "Match number": "17",
    "Scout name(your name)": "Bernice Lau",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Parked",
    "Problems with robot/driver": "Robot tipped over",
  },
  {
    Timestamp: "10/6/2018 8:57:35",
    "Team number": "2489",
    "Match number": "17",
    "Scout name(your name)": "Christopher Linhardt",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "5",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "5",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 8:59:12",
    "Team number": "4904",
    "Match number": "17",
    "Scout name(your name)": "Jake Ryan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "3",
    "Number of cubes dropped off in the scale (during teleop)": "4",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:16:54",
    "Team number": "7108",
    "Match number": "17",
    "Scout name(your name)": "Derek Duncan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "4",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "6",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:18:01",
    "Team number": "4904",
    "Match number": "17",
    "Scout name(your name)": "Jessie Lin",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "Robot tipped over",
  },
  {
    Timestamp: "10/6/2018 9:49:54",
    "Team number": "1700",
    "Match number": "17",
    "Scout name(your name)": "Audrey Lau",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:04:46",
    "Team number": "6884",
    "Match number": "18",
    "Scout name(your name)": "Kai Chang",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:05:24",
    "Team number": "4255",
    "Match number": "18",
    "Scout name(your name)": "Joshua Pan",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "2",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:05:55",
    "Team number": "5430",
    "Match number": "18",
    "Scout name(your name)": "Lavinie",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:06:17",
    "Team number": "199",
    "Match number": "18",
    "Scout name(your name)": "Christopher Linhardt",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:06:18",
    "Team number": "199",
    "Match number": "18",
    "Scout name(your name)": "Victoria Ng",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "3",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:06:38",
    "Team number": "5430",
    "Match number": "18",
    "Scout name(your name)": "Jake Ryan",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:06:54",
    "Team number": "2813",
    "Match number": "18",
    "Scout name(your name)": "Josephine Smith",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "4",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "4",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:12:40",
    "Team number": "6884",
    "Match number": "18",
    "Scout name(your name)": "Derek Duncan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:47:08",
    "Team number": "2473",
    "Match number": "18",
    "Scout name(your name)": "Madeleine Larson",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "3",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "3",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:13:45",
    "Team number": "4159",
    "Match number": "19",
    "Scout name(your name)": "Joshua Pan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "1",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:13:53",
    "Team number": "846",
    "Match number": "19",
    "Scout name(your name)": "Victoria Ng",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "1",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "6",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "4",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "1",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Lift partner",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:13:54",
    "Team number": "5104",
    "Match number": "19",
    "Scout name(your name)": "Lavinie ",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "5",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "1",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:14:11",
    "Team number": "4990",
    "Match number": "19",
    "Scout name(your name)": "Josephine Smith",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "4",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "3",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:20:47",
    "Team number": "668",
    "Match number": "19",
    "Scout name(your name)": "Joshua Pan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:28:56",
    "Team number": "114",
    "Match number": "19",
    "Scout name(your name)": "Kai Chang",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "5",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:49:22",
    "Team number": "1351",
    "Match number": "19",
    "Scout name(your name)": "Madeleine Larson",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "4",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "3",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "4",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:21:34",
    "Team number": "1868",
    "Match number": "20",
    "Scout name(your name)": "Josephine Smith",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "1",
    "Number of cubes picked up from the pyramid": "4",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "6",
    "Number of cubes dropped off in your alliance switch (during teleop)": "4",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:21:48",
    "Team number": "3501",
    "Match number": "20",
    "Scout name(your name)": "Victoria Ng",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "3",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:21:51",
    "Team number": "115",
    "Match number": "20",
    "Scout name(your name)": "Lavinie",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "2",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:28:21",
    "Team number": "253",
    "Match number": "20",
    "Scout name(your name)": "Joshua Pan",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "2",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "1",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:29:50",
    "Team number": "7308",
    "Match number": "20",
    "Scout name(your name)": "Kai Chang",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "5",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "5",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:51:32",
    "Team number": "1700",
    "Match number": "20",
    "Scout name(your name)": "Madeleine Larson",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:28:26",
    "Team number": "6814",
    "Match number": "21",
    "Scout name(your name)": "Victoria Ng",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:29:11",
    "Team number": "2473",
    "Match number": "21",
    "Scout name(your name)": "Josephine Smith",
    "Cross baseline during auto?": "Crashed into other robot",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "5",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "4",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:29:12",
    "Team number": "6884",
    "Match number": "21",
    "Scout name(your name)": "Lavinie",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:31:01",
    "Team number": "4765",
    "Match number": "21",
    "Scout name(your name)": "Kai Chang",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:53:02",
    "Team number": "972",
    "Match number": "21",
    "Scout name(your name)": "Madeleine Larson",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "7",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "3",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "5",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:37:51",
    "Team number": "2643",
    "Match number": "22",
    "Scout name(your name)": "Joshua Pan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "5",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "1",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:38:41",
    "Team number": "2854",
    "Match number": "22",
    "Scout name(your name)": "Victoria Ng",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "1",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "4",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:38:59",
    "Team number": "1458",
    "Match number": "22",
    "Scout name(your name)": "Josephine Smith",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "6",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "5",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Lift self only",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:39:00",
    "Team number": "2813",
    "Match number": "22",
    "Scout name(your name)": "Kai Chang",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for more than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:39:31",
    "Team number": "649",
    "Match number": "22",
    "Scout name(your name)": "Lavinie",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "5",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "4",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:54:16",
    "Team number": "3045",
    "Match number": "22",
    "Scout name(your name)": "Madeleine Larson",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Parked",
    "Problems with robot/driver": "Robot dead for more than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:45:14",
    "Team number": "4255",
    "Match number": "23",
    "Scout name(your name)": "Joshua Pan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:45:39",
    "Team number": "5430",
    "Match number": "23",
    "Scout name(your name)": "Josephine Smith",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:46:05",
    "Team number": "6418",
    "Match number": "23",
    "Scout name(your name)": "Lavinie",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for more than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:46:41",
    "Team number": "2489",
    "Match number": "23",
    "Scout name(your name)": "Victoria Ng",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "4",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:58:25",
    "Team number": "6174",
    "Match number": "23",
    "Scout name(your name)": "Madeleine Larson",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "6",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "2",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:54:42",
    "Team number": "6822",
    "Match number": "24",
    "Scout name(your name)": "Nathan",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "4",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:54:57",
    "Team number": "4904",
    "Match number": "24",
    "Scout name(your name)": "Thanawat",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:55:09",
    "Team number": "100",
    "Match number": "24",
    "Scout name(your name)": "Melanie Tam",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "4",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 9:55:45",
    "Team number": "1967",
    "Match number": "24",
    "Scout name(your name)": "Nikhita Law",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "6",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "4",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 9:58:19",
    "Team number": "199",
    "Match number": "24",
    "Scout name(your name)": "Madisen Young",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "1",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:06:55",
    "Team number": "649",
    "Match number": "25",
    "Scout name(your name)": "Thanawat",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "1",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "4",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "5",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:07:42",
    "Team number": "114",
    "Match number": "25",
    "Scout name(your name)": "Nathan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "5",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "6",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:08:16",
    "Team number": "253",
    "Match number": "25",
    "Scout name(your name)": "Nikhita Law",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:08:37",
    "Team number": "115",
    "Match number": "25",
    "Scout name(your name)": "Melanie Tam",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "5",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:14:57",
    "Team number": "3045",
    "Match number": "26",
    "Scout name(your name)": "Thanawat",
    "Cross baseline during auto?": "Foul",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "1",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot dead for more than 1 minute",
  },
  {
    Timestamp: "10/6/2018 10:15:46",
    "Team number": "1351",
    "Match number": "26",
    "Scout name(your name)": "Melanie Tam",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "4",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:15:59",
    "Team number": "2473",
    "Match number": "26",
    "Scout name(your name)": "Nathan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "5",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "5",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Parked",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 10:18:46",
    "Team number": "1458",
    "Match number": "26",
    "Scout name(your name)": "Nikhita Law",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:23:44",
    "Team number": "972",
    "Match number": "27",
    "Scout name(your name)": "Thanawat",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "3",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "1",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:24:14",
    "Team number": "751",
    "Match number": "27",
    "Scout name(your name)": "Bernice Lau",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "1",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver":
      "Robot tipped over, Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 10:24:53",
    "Team number": "2813",
    "Match number": "27",
    "Scout name(your name)": "Melanie Tam",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "3",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "3",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:25:05",
    "Team number": "4990",
    "Match number": "27",
    "Scout name(your name)": "Nathan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:27:59",
    "Team number": "1868",
    "Match number": "25",
    "Scout name(your name)": "Madisen Young",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "1",
    "Number of cubes picked up from the field": "5",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "4",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:29:23",
    "Team number": "670",
    "Match number": "24",
    "Scout name(your name)": "Normando Macaraeg ",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "6",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "2",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Lift self only",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:29:34",
    "Team number": "1700",
    "Match number": "26",
    "Scout name(your name)": "Madisen Young",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:32:46",
    "Team number": "6884",
    "Match number": "27",
    "Scout name(your name)": "Madisen Young",
    "Cross baseline during auto?": "No show",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot didn't show up",
  },
  {
    Timestamp: "10/6/2018 10:36:33",
    "Team number": "2643",
    "Match number": "25",
    "Scout name(your name)": "Normando Macaraeg ",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "2",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Parked",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:40:41",
    "Team number": "846",
    "Match number": "26",
    "Scout name(your name)": "Normando Macaraeg ",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "4",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Lift partner",
    "Problems with robot/driver": "Robot dead for less than 1 minute",
  },
  {
    Timestamp: "10/6/2018 10:45:09",
    "Team number": "5430",
    "Match number": "26",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:46:13",
    "Team number": "4765",
    "Match number": "28",
    "Scout name(your name)": "Madisen Young",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "1",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Lift self only",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:46:39",
    "Team number": "4904",
    "Match number": "28",
    "Scout name(your name)": "Melanie Tam",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:47:18",
    "Team number": "1987",
    "Match number": "27",
    "Scout name(your name)": "Normando Macaraeg ",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "5",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "5",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "Robot tipped over",
  },
  {
    Timestamp: "10/6/2018 10:48:48",
    "Team number": "2854",
    "Match number": "28",
    "Scout name(your name)": "Nikhita Law",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "2",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "3",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 10:56:40",
    "Team number": "3501",
    "Match number": "29",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "Robot tipped over",
  },
  {
    Timestamp: "10/6/2018 10:58:55",
    "Team number": "4765",
    "Match number": "28",
    "Scout name(your name)": "Samuel Kaplan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:00:51",
    "Team number": "174",
    "Match number": "29",
    "Scout name(your name)": "Samuel Kaplan",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "3",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Lift self only",
    "Problems with robot/driver":
      "Robot tipped over, No problems with robot., Robot didn't show up",
  },
  {
    Timestamp: "10/6/2018 11:07:16",
    "Team number": "100",
    "Match number": "30",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "4",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Lift self only",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:08:31",
    "Team number": "6814",
    "Match number": "30",
    "Scout name(your name)": "Jennifer",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "3",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:09:54",
    "Team number": "6418",
    "Match number": "30",
    "Scout name(your name)": "SeulAh Lee",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:10:08",
    "Team number": "6418",
    "Match number": "30",
    "Scout name(your name)": "SeulAh Lee",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "2",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:10:38",
    "Team number": "668",
    "Match number": "30",
    "Scout name(your name)": "Timmy Dang",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "1",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "4",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "2",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:19:32",
    "Team number": "1351",
    "Match number": "31",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "1",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "2",
    Endgame: "Failed to make it onto the scale area",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:25:50",
    "Team number": "3501",
    "Match number": "32",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "0",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "0",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "0",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "3",
    Endgame: "Lift self only",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:37:32",
    "Team number": "5104",
    "Match number": "33",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "7",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "1",
    "Number of cubes dropped off in the vault (during teleop)": "8",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "1",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:44:56",
    "Team number": "6418",
    "Match number": "34",
    "Scout name(your name)": "Xianzhi hua",
    "Cross baseline during auto?": "Yes",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "5",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "4",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "2",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
  {
    Timestamp: "10/6/2018 11:51:16",
    "Team number": "4765",
    "Match number": "35",
    "Scout name(your name)": "Xianzhi Hua",
    "Cross baseline during auto?": "No",
    "Number of cubes dropped off in the switch (during auto)": "0",
    "Number of cubes dropped off in the scale (during auto)": "0",
    "Number of cubes picked up from the pyramid": "3",
    "Number of cubes picked up from the portal": "0",
    "Number of cubes picked up from the field": "0",
    "Number of cubes dropped off in the vault (during teleop)": "2",
    "Number of cubes dropped off in the scale (during teleop)": "0",
    "Number of cubes dropped off in your alliance switch (during teleop)": "1",
    "Number of cubes dropped off in your opponent's alliance switch (during teleop)":
      "0",
    "Total number of cubes fumbled(robot lost control of cube)": "0",
    Endgame: "Climbed on ramp",
    "Problems with robot/driver": "No problems with robot.",
  },
]

export default data
