export default [
  {
    "Your Name": "Skinner",
    "Team Number": 0,
    "Event Code": "sfr",
    "Match Number": 16,
    "Robot Starting Platform": "level 1",
    "Leave Habitat": "FALSE",
    "Number of Hatch Panels(Sandstorm)": 37,
    "Number of Cargo(Sandstorm)": 34,
    "Number of Hatch Panels dropped(Sandstorm)": 45,
    "Number of Cargo dropped(Sandstorm)": 11,
    "Number of Hatch Panels(Teleop)": 46,
    "Number of Cargo(Teleop)": 29,
    "Number of Hatch Panels dropped(Teleop)": 40,
    "Number of Cargo dropped(Teleop)": 31,
    "Number of Fouls": 47,
    "Habitat Return": "level 1",
    "Rocket Completion": "FALSE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Oconnor",
    "Team Number": 0,
    "Event Code": "sfr",
    "Match Number": 38,
    "Robot Starting Platform": "level 1",
    "Leave Habitat": "FALSE",
    "Number of Hatch Panels(Sandstorm)": 8,
    "Number of Cargo(Sandstorm)": 22,
    "Number of Hatch Panels dropped(Sandstorm)": 8,
    "Number of Cargo dropped(Sandstorm)": 33,
    "Number of Hatch Panels(Teleop)": 42,
    "Number of Cargo(Teleop)": 9,
    "Number of Hatch Panels dropped(Teleop)": 32,
    "Number of Cargo dropped(Teleop)": 11,
    "Number of Fouls": 17,
    "Habitat Return": "level 1",
    "Rocket Completion": "FALSE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Travis",
    "Team Number": 5,
    "Event Code": "sfr",
    "Match Number": 11,
    "Robot Starting Platform": "level 2",
    "Leave Habitat": "TRUE",
    "Number of Hatch Panels(Sandstorm)": 35,
    "Number of Cargo(Sandstorm)": 32,
    "Number of Hatch Panels dropped(Sandstorm)": 42,
    "Number of Cargo dropped(Sandstorm)": 44,
    "Number of Hatch Panels(Teleop)": 40,
    "Number of Cargo(Teleop)": 49,
    "Number of Hatch Panels dropped(Teleop)": 4,
    "Number of Cargo dropped(Teleop)": 1,
    "Number of Fouls": 10,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Evangelina",
    "Team Number": 2,
    "Event Code": "sfr",
    "Match Number": 12,
    "Robot Starting Platform": "level 2",
    "Leave Habitat": "TRUE",
    "Number of Hatch Panels(Sandstorm)": 27,
    "Number of Cargo(Sandstorm)": 18,
    "Number of Hatch Panels dropped(Sandstorm)": 26,
    "Number of Cargo dropped(Sandstorm)": 36,
    "Number of Hatch Panels(Teleop)": 23,
    "Number of Cargo(Teleop)": 28,
    "Number of Hatch Panels dropped(Teleop)": 2,
    "Number of Cargo dropped(Teleop)": 29,
    "Number of Fouls": 7,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Jacobson",
    "Team Number": 2,
    "Event Code": "sfr",
    "Match Number": 49,
    "Robot Starting Platform": "level 1",
    "Leave Habitat": "TRUE",
    "Number of Hatch Panels(Sandstorm)": 13,
    "Number of Cargo(Sandstorm)": 4,
    "Number of Hatch Panels dropped(Sandstorm)": 49,
    "Number of Cargo dropped(Sandstorm)": 45,
    "Number of Hatch Panels(Teleop)": 0,
    "Number of Cargo(Teleop)": 9,
    "Number of Hatch Panels dropped(Teleop)": 4,
    "Number of Cargo dropped(Teleop)": 37,
    "Number of Fouls": 32,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Minerva",
    "Team Number": 3,
    "Event Code": "sfr",
    "Match Number": 20,
    "Robot Starting Platform": "level 1",
    "Leave Habitat": "FALSE",
    "Number of Hatch Panels(Sandstorm)": 25,
    "Number of Cargo(Sandstorm)": 32,
    "Number of Hatch Panels dropped(Sandstorm)": 29,
    "Number of Cargo dropped(Sandstorm)": 22,
    "Number of Hatch Panels(Teleop)": 18,
    "Number of Cargo(Teleop)": 50,
    "Number of Hatch Panels dropped(Teleop)": 41,
    "Number of Cargo dropped(Teleop)": 42,
    "Number of Fouls": 24,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Stafford",
    "Team Number": 5,
    "Event Code": "sfr",
    "Match Number": 9,
    "Robot Starting Platform": "level 2",
    "Leave Habitat": "FALSE",
    "Number of Hatch Panels(Sandstorm)": 35,
    "Number of Cargo(Sandstorm)": 6,
    "Number of Hatch Panels dropped(Sandstorm)": 4,
    "Number of Cargo dropped(Sandstorm)": 37,
    "Number of Hatch Panels(Teleop)": 31,
    "Number of Cargo(Teleop)": 14,
    "Number of Hatch Panels dropped(Teleop)": 23,
    "Number of Cargo dropped(Teleop)": 40,
    "Number of Fouls": 38,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Gregory",
    "Team Number": 3,
    "Event Code": "sfr",
    "Match Number": 26,
    "Robot Starting Platform": "level 1",
    "Leave Habitat": "TRUE",
    "Number of Hatch Panels(Sandstorm)": 11,
    "Number of Cargo(Sandstorm)": 25,
    "Number of Hatch Panels dropped(Sandstorm)": 18,
    "Number of Cargo dropped(Sandstorm)": 31,
    "Number of Hatch Panels(Teleop)": 32,
    "Number of Cargo(Teleop)": 36,
    "Number of Hatch Panels dropped(Teleop)": 18,
    "Number of Cargo dropped(Teleop)": 10,
    "Number of Fouls": 24,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Howell",
    "Team Number": 2,
    "Event Code": "sfr",
    "Match Number": 14,
    "Robot Starting Platform": "level 1",
    "Leave Habitat": "FALSE",
    "Number of Hatch Panels(Sandstorm)": 3,
    "Number of Cargo(Sandstorm)": 48,
    "Number of Hatch Panels dropped(Sandstorm)": 34,
    "Number of Cargo dropped(Sandstorm)": 43,
    "Number of Hatch Panels(Teleop)": 34,
    "Number of Cargo(Teleop)": 44,
    "Number of Hatch Panels dropped(Teleop)": 27,
    "Number of Cargo dropped(Teleop)": 22,
    "Number of Fouls": 25,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
  {
    "Your Name": "Irwin",
    "Team Number": 4,
    "Event Code": "sfr",
    "Match Number": 2,
    "Robot Starting Platform": "level 2",
    "Leave Habitat": "TRUE",
    "Number of Hatch Panels(Sandstorm)": 11,
    "Number of Cargo(Sandstorm)": 29,
    "Number of Hatch Panels dropped(Sandstorm)": 5,
    "Number of Cargo dropped(Sandstorm)": 37,
    "Number of Hatch Panels(Teleop)": 10,
    "Number of Cargo(Teleop)": 15,
    "Number of Hatch Panels dropped(Teleop)": 47,
    "Number of Cargo dropped(Teleop)": 36,
    "Number of Fouls": 29,
    "Habitat Return": "level 1",
    "Rocket Completion": "TRUE",
    "Robot Deadtime": "less than 5 seconds",
    Comments: "hello",
  },
]
